#!/usr/bin/env bash

PULSAR_GPU_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PULSAR_GPU_PREFIX="${PULSAR_GPU_PREFIX:-$PULSAR_GPU_ROOT/.local}"
CUDA_HOME="${CUDA_HOME:-/usr/local/cuda}"

export PULSAR_GPU_ROOT PULSAR_GPU_PREFIX CUDA_HOME
export CUDACXX="${CUDACXX:-$CUDA_HOME/bin/nvcc}"
export PATH="$PULSAR_GPU_PREFIX/bin:$CUDA_HOME/bin:$PATH"
export CMAKE_PREFIX_PATH="$PULSAR_GPU_PREFIX${CMAKE_PREFIX_PATH:+:$CMAKE_PREFIX_PATH}"
export LD_LIBRARY_PATH="$PULSAR_GPU_PREFIX/lib:$PULSAR_GPU_PREFIX/lib64:$CUDA_HOME/lib64${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
